"""
Environment file writer for Konnaxion instances.

This module is owned by the Konnaxion Agent because writing runtime env files
contains generated secrets and affects privileged runtime startup.

Rules enforced here:

- Capsules provide templates only.
- Real secrets are generated on install/update by the Agent.
- Instance env files live under /opt/konnaxion/instances/<INSTANCE_ID>/env/.
- KX_* variables use canonical names from kx_shared.konnaxion_constants.
- Writes are atomic and private by default.
"""

from __future__ import annotations

import os
import re
import secrets
import string
import tempfile
from dataclasses import dataclass, field
from pathlib import Path
from typing import Mapping

from kx_shared.konnaxion_constants import (
    DATABASE_ENV_DEFAULTS,
    DJANGO_ENV_DEFAULTS,
    FRONTEND_ENV_DEFAULTS,
    KX_ENV_DEFAULTS,
    REDIS_ENV_DEFAULTS,
    DockerService,
    ExposureMode,
    NetworkProfile,
    instance_backup_root,
    instance_compose_file,
    instance_env_dir,
)
from kx_shared.types import (
    CapsuleID,
    CapsuleVersion,
    EnvMap,
    Hostname,
    InstanceID,
    ParamVersion,
    URL,
)


ENV_FILE_MODE = 0o600
ENV_DIR_MODE = 0o700

DJANGO_ENV_FILENAME = "django.env"
POSTGRES_ENV_FILENAME = "postgres.env"
REDIS_ENV_FILENAME = "redis.env"
FRONTEND_ENV_FILENAME = "frontend.env"
KX_ENV_FILENAME = "konnaxion.env"

PLACEHOLDER_PATTERN = re.compile(r"^<[^>]+>$")
TEMPLATE_VAR_PATTERN = re.compile(r"\$\{([A-Z0-9_]+)\}|\{\{\s*([A-Z0-9_]+)\s*\}\}")

FORBIDDEN_SECRET_VALUES = frozenset(
    {
        "",
        "changeme",
        "change-me",
        "password",
        "secret",
        "admin",
        "konnaxion",
        "<GENERATED_ON_INSTALL>",
        "<POSTGRES_PASSWORD>",
        "<DJANGO_SECRET_KEY>",
    }
)

SECRET_ENV_KEYS = frozenset(
    {
        "DJANGO_SECRET_KEY",
        "POSTGRES_PASSWORD",
        "DATABASE_URL",
    }
)


@dataclass(frozen=True, slots=True)
class GeneratedSecrets:
    """Runtime secrets generated by the Agent for one instance."""

    django_secret_key: str
    postgres_password: str


@dataclass(frozen=True, slots=True)
class EnvFileSpec:
    """One env file to write."""

    filename: str
    values: EnvMap
    secret: bool = True


@dataclass(frozen=True, slots=True)
class InstanceEnvBundle:
    """All env files generated for an instance."""

    instance_id: InstanceID
    env_dir: Path
    files: tuple[Path, ...]
    host: Hostname
    public_url: URL
    api_base_url: URL


@dataclass(frozen=True, slots=True)
class InstanceEnvContext:
    """Input context for generating canonical instance env files."""

    instance_id: InstanceID
    capsule_id: CapsuleID
    capsule_version: CapsuleVersion
    param_version: ParamVersion
    app_version: str
    network_profile: NetworkProfile
    exposure_mode: ExposureMode
    host: Hostname
    public_mode_enabled: bool = False
    public_mode_expires_at: str = ""
    extra_kx_env: Mapping[str, str] = field(default_factory=dict)
    extra_django_env: Mapping[str, str] = field(default_factory=dict)
    extra_postgres_env: Mapping[str, str] = field(default_factory=dict)
    extra_redis_env: Mapping[str, str] = field(default_factory=dict)
    extra_frontend_env: Mapping[str, str] = field(default_factory=dict)


def generate_secret_key(length: int = 64) -> str:
    """Generate a Django-compatible random secret key."""

    alphabet = string.ascii_letters + string.digits + "!@#$%^&*(-_=+)"
    return "".join(secrets.choice(alphabet) for _ in range(length))


def generate_password(length: int = 40) -> str:
    """Generate a strong password suitable for PostgreSQL."""

    alphabet = string.ascii_letters + string.digits + "-_"
    return "".join(secrets.choice(alphabet) for _ in range(length))


def generate_runtime_secrets() -> GeneratedSecrets:
    """Generate all secrets required for a new Konnaxion instance."""

    return GeneratedSecrets(
        django_secret_key=generate_secret_key(),
        postgres_password=generate_password(),
    )


def normalize_host(host: str | Hostname) -> Hostname:
    """Normalize a configured Konnaxion host value."""

    normalized = str(host).strip().rstrip("/")
    if not normalized:
        raise ValueError("host must not be empty")
    if "://" in normalized:
        normalized = normalized.split("://", 1)[1].strip().rstrip("/")
    return Hostname(normalized)


def build_base_url(host: str | Hostname) -> URL:
    """Build the canonical HTTPS base URL for a host."""

    normalized = normalize_host(host)
    return URL(f"https://{normalized}")


def build_api_base_url(host: str | Hostname) -> URL:
    """Build the canonical frontend API base URL."""

    return URL(f"{build_base_url(host)}/api")


def is_placeholder(value: str) -> bool:
    """Return true if a value is an unresolved template placeholder."""

    return bool(PLACEHOLDER_PATTERN.fullmatch(value.strip()))


def validate_secret_value(key: str, value: str) -> None:
    """Reject empty, placeholder, or known-default secret values."""

    normalized = value.strip()
    if normalized in FORBIDDEN_SECRET_VALUES or is_placeholder(normalized):
        raise ValueError(f"{key} must be generated and must not use a default placeholder")


def validate_no_unresolved_placeholders(values: Mapping[str, str]) -> None:
    """Reject env maps containing unresolved placeholders."""

    for key, value in values.items():
        if is_placeholder(value):
            raise ValueError(f"{key} contains unresolved placeholder {value!r}")


def validate_secret_env(values: Mapping[str, str]) -> None:
    """Validate all known secret env values."""

    for key in SECRET_ENV_KEYS:
        if key in values:
            validate_secret_value(key, values[key])


def merge_env(*maps: Mapping[str, str]) -> EnvMap:
    """Merge env mappings from left to right, dropping None-like values."""

    merged: EnvMap = {}
    for mapping in maps:
        for key, value in mapping.items():
            if value is None:
                continue
            merged[str(key)] = str(value)
    return merged


def build_database_url(postgres_password: str) -> str:
    """Build the canonical internal PostgreSQL DATABASE_URL."""

    return f"postgres://konnaxion:{postgres_password}@{DockerService.POSTGRES.value}:5432/konnaxion"


def build_kx_env(context: InstanceEnvContext) -> EnvMap:
    """Build canonical KX_* instance environment variables."""

    instance_id = str(context.instance_id)
    compose_file = instance_compose_file(instance_id)
    backup_root = instance_backup_root(instance_id)

    base = merge_env(
        KX_ENV_DEFAULTS,
        {
            "KX_INSTANCE_ID": instance_id,
            "KX_CAPSULE_ID": str(context.capsule_id),
            "KX_CAPSULE_VERSION": str(context.capsule_version),
            "KX_APP_VERSION": context.app_version,
            "KX_PARAM_VERSION": str(context.param_version),
            "KX_NETWORK_PROFILE": context.network_profile.value,
            "KX_EXPOSURE_MODE": context.exposure_mode.value,
            "KX_PUBLIC_MODE_ENABLED": "true" if context.public_mode_enabled else "false",
            "KX_PUBLIC_MODE_EXPIRES_AT": context.public_mode_expires_at,
            "KX_COMPOSE_FILE": str(compose_file),
            "KX_BACKUP_DIR": str(backup_root),
            "KX_HOST": str(context.host),
        },
        context.extra_kx_env,
    )

    if base["KX_PUBLIC_MODE_ENABLED"] == "true" and not base.get("KX_PUBLIC_MODE_EXPIRES_AT"):
        raise ValueError("KX_PUBLIC_MODE_EXPIRES_AT is mandatory when public mode is enabled")

    return base


def build_django_env(context: InstanceEnvContext, runtime_secrets: GeneratedSecrets) -> EnvMap:
    """Build canonical Django runtime env."""

    host = normalize_host(context.host)
    values = merge_env(
        DJANGO_ENV_DEFAULTS,
        {
            "DJANGO_SECRET_KEY": runtime_secrets.django_secret_key,
            "DJANGO_ALLOWED_HOSTS": str(host),
            "DATABASE_URL": build_database_url(runtime_secrets.postgres_password),
        },
        context.extra_django_env,
    )
    validate_secret_env(values)
    validate_no_unresolved_placeholders(values)
    return values


def build_postgres_env(context: InstanceEnvContext, runtime_secrets: GeneratedSecrets) -> EnvMap:
    """Build canonical PostgreSQL runtime env."""

    values = merge_env(
        DATABASE_ENV_DEFAULTS,
        {
            "POSTGRES_PASSWORD": runtime_secrets.postgres_password,
        },
        context.extra_postgres_env,
    )
    validate_secret_env(values)
    validate_no_unresolved_placeholders(values)
    return values


def build_redis_env(context: InstanceEnvContext) -> EnvMap:
    """Build canonical Redis/Celery runtime env."""

    values = merge_env(REDIS_ENV_DEFAULTS, context.extra_redis_env)
    validate_no_unresolved_placeholders(values)
    return values


def build_frontend_env(context: InstanceEnvContext) -> EnvMap:
    """Build canonical Next.js runtime env."""

    values = merge_env(
        FRONTEND_ENV_DEFAULTS,
        {
            "NEXT_PUBLIC_API_BASE": str(build_api_base_url(context.host)),
            "NEXT_PUBLIC_BACKEND_BASE": str(build_base_url(context.host)),
        },
        context.extra_frontend_env,
    )
    validate_no_unresolved_placeholders(values)
    return values


def build_env_file_specs(
    context: InstanceEnvContext,
    runtime_secrets: GeneratedSecrets,
) -> tuple[EnvFileSpec, ...]:
    """Build all canonical env file specs for an instance."""

    return (
        EnvFileSpec(KX_ENV_FILENAME, build_kx_env(context), secret=False),
        EnvFileSpec(DJANGO_ENV_FILENAME, build_django_env(context, runtime_secrets), secret=True),
        EnvFileSpec(POSTGRES_ENV_FILENAME, build_postgres_env(context, runtime_secrets), secret=True),
        EnvFileSpec(REDIS_ENV_FILENAME, build_redis_env(context), secret=False),
        EnvFileSpec(FRONTEND_ENV_FILENAME, build_frontend_env(context), secret=False),
    )


def format_env_value(value: str) -> str:
    """Format one env value for dotenv-compatible files."""

    if value == "":
        return ""

    if re.search(r"\s|#|'|\"|\\|\$", value):
        escaped = value.replace("\\", "\\\\").replace('"', '\\"')
        return f'"{escaped}"'

    return value


def serialize_env(values: Mapping[str, str]) -> str:
    """Serialize an env mapping to deterministic dotenv text."""

    lines = []
    for key in sorted(values):
        value = values[key]
        if not re.fullmatch(r"[A-Z][A-Z0-9_]*", key):
            raise ValueError(f"invalid env key: {key!r}")
        lines.append(f"{key}={format_env_value(str(value))}")
    return "\n".join(lines) + "\n"


def parse_env_template(path: Path | str) -> EnvMap:
    """Parse a simple KEY=value env template.

    Comments and blank lines are ignored. The parser intentionally does not
    evaluate shell syntax.
    """

    template_path = Path(path)
    values: EnvMap = {}

    for line_number, raw_line in enumerate(template_path.read_text(encoding="utf-8").splitlines(), start=1):
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        if "=" not in line:
            raise ValueError(f"{template_path}:{line_number}: expected KEY=value")
        key, value = line.split("=", 1)
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        if not re.fullmatch(r"[A-Z][A-Z0-9_]*", key):
            raise ValueError(f"{template_path}:{line_number}: invalid env key {key!r}")
        values[key] = value

    return values


def render_template_value(value: str, variables: Mapping[str, str]) -> str:
    """Render ${VAR} and {{ VAR }} placeholders from a variable map."""

    def replace(match: re.Match[str]) -> str:
        key = match.group(1) or match.group(2)
        if key not in variables:
            raise ValueError(f"missing template variable {key}")
        return variables[key]

    return TEMPLATE_VAR_PATTERN.sub(replace, value)


def render_env_template(template: Mapping[str, str], variables: Mapping[str, str]) -> EnvMap:
    """Render all values in an env template using a variable map."""

    return {
        key: render_template_value(value, variables)
        for key, value in template.items()
    }


def ensure_private_env_dir(path: Path) -> None:
    """Create and chmod the instance env directory."""

    path.mkdir(parents=True, exist_ok=True)
    try:
        os.chmod(path, ENV_DIR_MODE)
    except PermissionError:
        # Some test/dev filesystems do not permit chmod.
        pass


def atomic_write_text(path: Path, content: str, *, mode: int = ENV_FILE_MODE) -> None:
    """Atomically write text to a file and apply private permissions."""

    path.parent.mkdir(parents=True, exist_ok=True)

    with tempfile.NamedTemporaryFile(
        "w",
        delete=False,
        dir=str(path.parent),
        encoding="utf-8",
        prefix=f".{path.name}.",
    ) as tmp:
        tmp.write(content)
        tmp.flush()
        os.fsync(tmp.fileno())
        tmp_path = Path(tmp.name)

    try:
        os.chmod(tmp_path, mode)
    except PermissionError:
        pass

    tmp_path.replace(path)


def write_env_file(path: Path, values: Mapping[str, str], *, secret: bool = True) -> Path:
    """Write one env file with deterministic ordering."""

    validate_no_unresolved_placeholders(values)
    if secret:
        validate_secret_env(values)

    atomic_write_text(path, serialize_env(values), mode=ENV_FILE_MODE)
    return path


def write_instance_env_files(
    context: InstanceEnvContext,
    runtime_secrets: GeneratedSecrets | None = None,
    *,
    overwrite: bool = True,
) -> InstanceEnvBundle:
    """Generate and write canonical env files for a Konnaxion instance."""

    secrets_to_write = runtime_secrets or generate_runtime_secrets()
    target_env_dir = instance_env_dir(str(context.instance_id))
    ensure_private_env_dir(target_env_dir)

    specs = build_env_file_specs(context, secrets_to_write)
    written: list[Path] = []

    for spec in specs:
        path = target_env_dir / spec.filename
        if path.exists() and not overwrite:
            raise FileExistsError(f"env file already exists: {path}")
        write_env_file(path, spec.values, secret=spec.secret)
        written.append(path)

    return InstanceEnvBundle(
        instance_id=context.instance_id,
        env_dir=target_env_dir,
        files=tuple(written),
        host=normalize_host(context.host),
        public_url=build_base_url(context.host),
        api_base_url=build_api_base_url(context.host),
    )


def load_existing_env_file(path: Path | str) -> EnvMap:
    """Load an existing generated env file.

    This is intentionally conservative and supports only KEY=value lines.
    """

    return parse_env_template(path)


def load_instance_env(instance_id: InstanceID | str) -> EnvMap:
    """Load all canonical env files for an instance into one map."""

    target_env_dir = instance_env_dir(str(instance_id))
    merged: EnvMap = {}

    for filename in (
        KX_ENV_FILENAME,
        DJANGO_ENV_FILENAME,
        POSTGRES_ENV_FILENAME,
        REDIS_ENV_FILENAME,
        FRONTEND_ENV_FILENAME,
    ):
        path = target_env_dir / filename
        if path.exists():
            merged.update(load_existing_env_file(path))

    return merged


def env_file_paths(instance_id: InstanceID | str) -> tuple[Path, ...]:
    """Return canonical env file paths for an instance."""

    target_env_dir = instance_env_dir(str(instance_id))
    return (
        target_env_dir / KX_ENV_FILENAME,
        target_env_dir / DJANGO_ENV_FILENAME,
        target_env_dir / POSTGRES_ENV_FILENAME,
        target_env_dir / REDIS_ENV_FILENAME,
        target_env_dir / FRONTEND_ENV_FILENAME,
    )


def assert_env_files_exist(instance_id: InstanceID | str) -> None:
    """Raise if any canonical env file is missing."""

    missing = [path for path in env_file_paths(instance_id) if not path.exists()]
    if missing:
        missing_text = ", ".join(str(path) for path in missing)
        raise FileNotFoundError(f"missing env files for instance {instance_id}: {missing_text}")


def validate_written_env(instance_id: InstanceID | str) -> None:
    """Validate generated env files for startup readiness."""

    assert_env_files_exist(instance_id)
    values = load_instance_env(instance_id)

    required = {
        "KX_INSTANCE_ID",
        "KX_CAPSULE_ID",
        "KX_CAPSULE_VERSION",
        "KX_APP_VERSION",
        "KX_PARAM_VERSION",
        "KX_NETWORK_PROFILE",
        "KX_EXPOSURE_MODE",
        "KX_BACKUP_DIR",
        "KX_COMPOSE_FILE",
        "KX_HOST",
        "DJANGO_SECRET_KEY",
        "DJANGO_ALLOWED_HOSTS",
        "DATABASE_URL",
        "POSTGRES_PASSWORD",
        "POSTGRES_HOST",
        "POSTGRES_PORT",
        "POSTGRES_DB",
        "POSTGRES_USER",
        "REDIS_URL",
        "CELERY_BROKER_URL",
        "CELERY_RESULT_BACKEND",
        "NEXT_PUBLIC_API_BASE",
        "NEXT_PUBLIC_BACKEND_BASE",
    }

    missing = sorted(required - set(values))
    if missing:
        raise ValueError(f"missing required env keys: {', '.join(missing)}")

    validate_secret_env(values)
    validate_no_unresolved_placeholders(values)

    NetworkProfile(values["KX_NETWORK_PROFILE"])
    ExposureMode(values["KX_EXPOSURE_MODE"])


__all__ = [
    "DJANGO_ENV_FILENAME",
    "ENV_DIR_MODE",
    "ENV_FILE_MODE",
    "FORBIDDEN_SECRET_VALUES",
    "FRONTEND_ENV_FILENAME",
    "GeneratedSecrets",
    "InstanceEnvBundle",
    "InstanceEnvContext",
    "KX_ENV_FILENAME",
    "POSTGRES_ENV_FILENAME",
    "REDIS_ENV_FILENAME",
    "SECRET_ENV_KEYS",
    "TEMPLATE_VAR_PATTERN",
    "atomic_write_text",
    "assert_env_files_exist",
    "build_api_base_url",
    "build_base_url",
    "build_database_url",
    "build_django_env",
    "build_env_file_specs",
    "build_frontend_env",
    "build_kx_env",
    "build_postgres_env",
    "build_redis_env",
    "env_file_paths",
    "format_env_value",
    "generate_password",
    "generate_runtime_secrets",
    "generate_secret_key",
    "is_placeholder",
    "load_existing_env_file",
    "load_instance_env",
    "merge_env",
    "normalize_host",
    "parse_env_template",
    "render_env_template",
    "render_template_value",
    "serialize_env",
    "validate_no_unresolved_placeholders",
    "validate_secret_env",
    "validate_secret_value",
    "validate_written_env",
    "write_env_file",
    "write_instance_env_files",
]
