"""
Shared Konnaxion package.

This package contains canonical constants, enums, path helpers, shared
types, and validation utilities used by the Konnaxion Capsule Manager,
Konnaxion Agent, Konnaxion Capsule Builder, and kx CLI.
"""

from .konnaxion_constants import (
    AGENT_NAME,
    APP_VERSION,
    BackupStatus,
    BLOCKING_SECURITY_CHECKS,
    BOX_NAME,
    BUILDER_NAME,
    CAPSULE_EXTENSION,
    CAPSULE_FILENAME_PATTERN,
    CLI_NAME,
    DEFAULT_CAPSULE_ID,
    DEFAULT_CAPSULE_VERSION,
    DEFAULT_CHANNEL,
    DEFAULT_EXPOSURE_MODE,
    DEFAULT_INSTANCE_ID,
    DEFAULT_NETWORK_PROFILE,
    DEFAULT_PUBLIC_MODE_ENABLED,
    DEFAULT_RELEASE_ID,
    DockerService,
    ExposureMode,
    INSTANCE_NAME,
    InstanceState,
    KX_AGENT_DIR,
    KX_BACKUPS_ROOT,
    KX_CAPSULES_DIR,
    KX_ENV_DEFAULTS,
    KX_INSTANCES_DIR,
    KX_MANAGER_DIR,
    KX_RELEASES_DIR,
    KX_ROOT,
    KX_SHARED_DIR,
    MANAGER_NAME,
    NetworkProfile,
    PARAM_VERSION,
    PRODUCT_NAME,
    RestoreStatus,
    RollbackStatus,
    SecurityGateCheck,
    SecurityGateStatus,
)

__all__ = [
    "AGENT_NAME",
    "APP_VERSION",
    "BackupStatus",
    "BLOCKING_SECURITY_CHECKS",
    "BOX_NAME",
    "BUILDER_NAME",
    "CAPSULE_EXTENSION",
    "CAPSULE_FILENAME_PATTERN",
    "CLI_NAME",
    "DEFAULT_CAPSULE_ID",
    "DEFAULT_CAPSULE_VERSION",
    "DEFAULT_CHANNEL",
    "DEFAULT_EXPOSURE_MODE",
    "DEFAULT_INSTANCE_ID",
    "DEFAULT_NETWORK_PROFILE",
    "DEFAULT_PUBLIC_MODE_ENABLED",
    "DEFAULT_RELEASE_ID",
    "DockerService",
    "ExposureMode",
    "INSTANCE_NAME",
    "InstanceState",
    "KX_AGENT_DIR",
    "KX_BACKUPS_ROOT",
    "KX_CAPSULES_DIR",
    "KX_ENV_DEFAULTS",
    "KX_INSTANCES_DIR",
    "KX_MANAGER_DIR",
    "KX_RELEASES_DIR",
    "KX_ROOT",
    "KX_SHARED_DIR",
    "MANAGER_NAME",
    "NetworkProfile",
    "PARAM_VERSION",
    "PRODUCT_NAME",
    "RestoreStatus",
    "RollbackStatus",
    "SecurityGateCheck",
    "SecurityGateStatus",
]