"""Shared HTML rendering helpers for the FastAPI Manager GUI.

This module is presentation-only.

It may render Manager DTOs/view models, form controls, action buttons, and
safe result panels, but it must not dispatch GUI actions, execute shell
commands, control Docker, modify firewall state, or perform backup/runtime
operations.
"""

from __future__ import annotations

from dataclasses import asdict, dataclass, is_dataclass
from enum import Enum
from html import escape
import json
from typing import Any, Iterable, Mapping, Sequence

from fastapi.responses import HTMLResponse

try:
    from kx_shared.konnaxion_constants import APP_VERSION, PARAM_VERSION
except Exception:  # pragma: no cover - development fallback only.
    APP_VERSION = "v14"
    PARAM_VERSION = "kx-param-2026.04.30"

try:
    from kx_manager.ui.static import (
        ACTION_BASE_PATH,
        NAV_ITEMS,
        UI_BASE_PATH,
        route_for_action as _route_for_action,
    )
except Exception:  # pragma: no cover - staged build compatibility
    UI_BASE_PATH = "/ui"
    ACTION_BASE_PATH = "/ui/actions"
    NAV_ITEMS = (
        ("Dashboard", "/ui"),
        ("Capsules", "/ui/capsules"),
        ("Instances", "/ui/instances"),
        ("Targets", "/ui/targets"),
        ("Security", "/ui/security"),
        ("Network", "/ui/network"),
        ("Backups", "/ui/backups"),
        ("Restore", "/ui/restore"),
        ("Logs", "/ui/logs"),
        ("Health", "/ui/health"),
        ("Settings", "/ui/settings"),
        ("About", "/ui/about"),
    )

    def _route_for_action(action: Any) -> str:
        value = str(getattr(action, "value", action)).strip()
        return f"{ACTION_BASE_PATH}/{value.replace('_', '-')}"


PRODUCT_NAME = "Konnaxion"
MANAGER_NAME = "Konnaxion Capsule Manager"
DEFAULT_TITLE = MANAGER_NAME


class SafeHtml(str):
    """Marker type for HTML generated by this renderer."""


def safe_html(value: str) -> SafeHtml:
    """Mark internally generated HTML as safe for nested rendering."""

    return SafeHtml(value)


@dataclass(frozen=True)
class NavItem:
    label: str
    href: str
    active: bool = False


@dataclass(frozen=True)
class SelectOption:
    value: str
    label: str
    selected: bool = False


@dataclass(frozen=True)
class FormField:
    name: str
    label: str
    value: Any = ""
    field_type: str = "text"
    required: bool = False
    placeholder: str = ""
    help_text: str = ""
    options: Sequence[SelectOption | tuple[str, str] | str] | None = None


BASE_CSS = """
:root {
  color-scheme: light;
  --bg: #f6f8fb;
  --panel: #ffffff;
  --text: #172033;
  --muted: #667085;
  --line: #d9e0ea;
  --accent: #204a87;
  --accent-dark: #173866;
  --ok: #166534;
  --warn: #92400e;
  --bad: #991b1b;
  --info: #1d4ed8;
  --soft-ok: #dcfce7;
  --soft-warn: #fef3c7;
  --soft-bad: #fee2e2;
  --soft-info: #dbeafe;
}

* { box-sizing: border-box; }

body {
  margin: 0;
  background: var(--bg);
  color: var(--text);
  font: 14px/1.45 system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
}

a {
  color: var(--accent);
  text-decoration: none;
}

a:hover { text-decoration: underline; }

.kx-shell {
  min-height: 100vh;
  display: flex;
  flex-direction: column;
}

.kx-header {
  background: var(--panel);
  border-bottom: 1px solid var(--line);
  padding: 16px 24px;
}

.kx-title {
  margin: 0;
  font-size: 22px;
}

.kx-subtitle {
  margin: 4px 0 0;
  color: var(--muted);
}

.kx-nav {
  display: flex;
  flex-wrap: wrap;
  gap: 8px;
  padding: 12px 24px;
  background: var(--panel);
  border-bottom: 1px solid var(--line);
}

.kx-nav a {
  border: 1px solid var(--line);
  border-radius: 999px;
  padding: 6px 10px;
  background: #fff;
}

.kx-nav a.active {
  background: var(--accent);
  color: #fff;
  border-color: var(--accent);
}

.kx-main {
  width: min(1240px, 100%);
  margin: 0 auto;
  padding: 24px;
}

.kx-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(280px, 1fr));
  gap: 16px;
}

.kx-card {
  background: var(--panel);
  border: 1px solid var(--line);
  border-radius: 14px;
  padding: 16px;
  box-shadow: 0 1px 2px rgba(16, 24, 40, 0.04);
}

.kx-card h2,
.kx-card h3 {
  margin-top: 0;
}

.kx-muted {
  color: var(--muted);
}

.kx-actions {
  display: flex;
  flex-wrap: wrap;
  gap: 8px;
  align-items: center;
  margin-top: 12px;
}

.kx-button,
button.kx-button {
  appearance: none;
  border: 1px solid var(--accent);
  border-radius: 8px;
  background: var(--accent);
  color: #fff;
  cursor: pointer;
  display: inline-flex;
  align-items: center;
  justify-content: center;
  min-height: 36px;
  padding: 7px 12px;
  font-weight: 600;
}

.kx-button.secondary,
button.kx-button.secondary {
  background: #fff;
  color: var(--accent);
}

.kx-button.danger,
button.kx-button.danger {
  background: var(--bad);
  border-color: var(--bad);
}

.kx-button:disabled {
  opacity: 0.5;
  cursor: not-allowed;
}

.kx-form {
  display: grid;
  gap: 12px;
}

.kx-field label {
  display: block;
  font-weight: 650;
  margin-bottom: 4px;
}

.kx-field input,
.kx-field select,
.kx-field textarea {
  width: 100%;
  border: 1px solid var(--line);
  border-radius: 8px;
  padding: 8px 10px;
  font: inherit;
  background: #fff;
}

.kx-field textarea {
  min-height: 96px;
  resize: vertical;
}

.kx-help {
  color: var(--muted);
  font-size: 12px;
  margin-top: 4px;
}

.kx-badge {
  display: inline-flex;
  align-items: center;
  border-radius: 999px;
  padding: 3px 8px;
  font-size: 12px;
  font-weight: 650;
  border: 1px solid var(--line);
  background: #fff;
}

.kx-badge.ok {
  color: var(--ok);
  background: var(--soft-ok);
  border-color: #bbf7d0;
}

.kx-badge.warn {
  color: var(--warn);
  background: var(--soft-warn);
  border-color: #fde68a;
}

.kx-badge.error {
  color: var(--bad);
  background: var(--soft-bad);
  border-color: #fecaca;
}

.kx-badge.info {
  color: var(--info);
  background: var(--soft-info);
  border-color: #bfdbfe;
}

.kx-result {
  margin-bottom: 16px;
}

.kx-result.ok { border-left: 5px solid var(--ok); }
.kx-result.error { border-left: 5px solid var(--bad); }
.kx-result.info { border-left: 5px solid var(--info); }
.kx-result.warn { border-left: 5px solid var(--warn); }

.kx-table {
  width: 100%;
  border-collapse: collapse;
  overflow: hidden;
}

.kx-table th,
.kx-table td {
  border-bottom: 1px solid var(--line);
  padding: 8px;
  text-align: left;
  vertical-align: top;
}

.kx-table th {
  color: var(--muted);
  font-size: 12px;
  text-transform: uppercase;
  letter-spacing: .03em;
}

.kx-defs {
  display: grid;
  grid-template-columns: max-content 1fr;
  gap: 6px 12px;
}

.kx-defs dt {
  color: var(--muted);
  font-weight: 650;
}

.kx-defs dd {
  margin: 0;
  min-width: 0;
  word-break: break-word;
}

.kx-log,
pre.kx-json {
  margin: 0;
  padding: 12px;
  overflow: auto;
  border-radius: 10px;
  background: #101828;
  color: #f9fafb;
  font: 12px/1.45 ui-monospace, SFMono-Regular, Menlo, Consolas, monospace;
  max-height: 520px;
}

.kx-footer {
  color: var(--muted);
  padding: 16px 24px 24px;
  text-align: center;
}
"""


def raw_value(value: Any) -> Any:
    """Return a scalar value for enums and enum-like values."""

    return getattr(value, "value", value)


def h(value: Any) -> str:
    """Escape text for safe HTML rendering."""

    if value is None:
        return ""
    return escape(str(raw_value(value)), quote=True)


def attr(value: Any) -> str:
    """Escape an HTML attribute value."""

    return h(value)


def css_class(*parts: str | None | bool) -> str:
    """Join CSS class fragments while ignoring blanks and false values."""

    return " ".join(str(part) for part in parts if part)


def to_mapping(value: Any) -> Mapping[str, Any]:
    """Convert DTO/view models to dictionaries when possible."""

    if isinstance(value, Mapping):
        return value

    if is_dataclass(value):
        return asdict(value)

    to_dict = getattr(value, "to_dict", None)
    if callable(to_dict):
        data = to_dict()
        if isinstance(data, Mapping):
            return data

    model_dump = getattr(value, "model_dump", None)
    if callable(model_dump):
        data = model_dump()
        if isinstance(data, Mapping):
            return data

    dict_method = getattr(value, "dict", None)
    if callable(dict_method):
        data = dict_method()
        if isinstance(data, Mapping):
            return data

    return {}


def json_text(value: Any) -> str:
    """Serialize arbitrary data for display."""

    def default(item: Any) -> Any:
        if isinstance(item, Enum):
            return item.value

        if is_dataclass(item):
            return asdict(item)

        to_dict = getattr(item, "to_dict", None)
        if callable(to_dict):
            return to_dict()

        model_dump = getattr(item, "model_dump", None)
        if callable(model_dump):
            return model_dump()

        return str(item)

    try:
        return json.dumps(value, indent=2, sort_keys=True, default=default)
    except TypeError:
        return str(value)


def safe_href(href: str | None) -> str:
    """Return an escaped safe link target."""

    raw = (href or "#").strip()
    lowered = raw.lower()

    if not raw or lowered.startswith(("javascript:", "data:", "vbscript:")):
        return "#"

    return attr(raw)


def action_url(action: Any) -> str:
    """Build the canonical UI action route for a UiAction/string value."""

    value = raw_value(action)

    try:
        return _route_for_action(value)
    except Exception:
        text = str(value).strip()
        if not text:
            return "#"
        return f"{ACTION_BASE_PATH}/{text.replace('_', '-')}"


def _form_action_href(action: str) -> str:
    raw = str(action).strip()
    lowered = raw.lower()

    if (
        raw.startswith("/")
        or raw.startswith("#")
        or lowered.startswith(("http://", "https://"))
    ):
        return raw

    return action_url(raw)


def default_nav(active_href: str = UI_BASE_PATH) -> list[NavItem]:
    """Return default local GUI navigation."""

    return [
        NavItem(label=label, href=href, active=href == active_href)
        for label, href in NAV_ITEMS
    ]


def render_nav(items: Sequence[NavItem | Mapping[str, Any]]) -> str:
    """Render the top navigation bar."""

    links: list[str] = []

    for item in items:
        if isinstance(item, Mapping):
            label = item.get("label", "")
            href = item.get("href", "#")
            active = bool(item.get("active"))
        else:
            label = item.label
            href = item.href
            active = item.active

        links.append(
            f'<a class="{css_class("active" if active else None)}" '
            f'href="{safe_href(str(href))}">{h(label)}</a>'
        )

    return safe_html(f'<nav class="kx-nav">{"".join(links)}</nav>')


def render_header(title: str, subtitle: str = "") -> str:
    """Render page header."""

    subtitle_html = f'<p class="kx-subtitle">{h(subtitle)}</p>' if subtitle else ""

    return safe_html(
        '<header class="kx-header">'
        f'<h1 class="kx-title">{h(title)}</h1>'
        f"{subtitle_html}"
        "</header>"
    )


def render_layout(
    title: str,
    body: str,
    *,
    subtitle: str = "",
    active_href: str = UI_BASE_PATH,
    nav_items: Sequence[NavItem | Mapping[str, Any]] | None = None,
    result: Any | None = None,
    extra_head: str = "",
) -> str:
    """Render a full HTML document."""

    page_title = f"{title} · {MANAGER_NAME}" if title != MANAGER_NAME else title
    nav_html = render_nav(nav_items or default_nav(active_href))
    result_html = render_result_panel(result)

    return f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{h(page_title)}</title>
  <style>{BASE_CSS}</style>
  {extra_head}
</head>
<body>
  <div class="kx-shell">
    {render_header(title, subtitle)}
    {nav_html}
    <main class="kx-main">
      {result_html}
      {body}
    </main>
    <footer class="kx-footer">{h(PRODUCT_NAME)} · local Manager GUI · {h(APP_VERSION)} · {h(PARAM_VERSION)}</footer>
  </div>
</body>
</html>"""


def html_response(
    title: str,
    body: str,
    *,
    subtitle: str = "",
    active_href: str = UI_BASE_PATH,
    nav_items: Sequence[NavItem | Mapping[str, Any]] | None = None,
    result: Any | None = None,
    status_code: int = 200,
) -> HTMLResponse:
    """Return a FastAPI HTMLResponse."""

    return HTMLResponse(
        content=render_layout(
            title,
            body,
            subtitle=subtitle,
            active_href=active_href,
            nav_items=nav_items,
            result=result,
        ),
        status_code=status_code,
    )


def render_page(
    title: str,
    body: str,
    *,
    subtitle: str = "",
    active_href: str = UI_BASE_PATH,
    result: Any | None = None,
    status_code: int = 200,
) -> HTMLResponse:
    """Compatibility wrapper for UI route handlers."""

    return html_response(
        title,
        body,
        subtitle=subtitle,
        active_href=active_href,
        result=result,
        status_code=status_code,
    )


def render_error_page(
    message: str,
    *,
    title: str = "Error",
    status_code: int = 400,
) -> HTMLResponse:
    """Render a safe error page."""

    body = render_card(title, f"<p>{h(message)}</p>", classes="kx-result error")
    return html_response(title, body, status_code=status_code)


def render_badge(label: Any, tone: str = "info") -> str:
    """Render a small status badge."""

    normalized = tone if tone in {"ok", "warn", "error", "info"} else "info"
    return safe_html(f'<span class="kx-badge {normalized}">{h(label)}</span>')


def status_tone(value: Any) -> str:
    """Map canonical status-ish values to badge tones."""

    text = str(raw_value(value) or "").lower()

    if text in {
        "ok",
        "pass",
        "passed",
        "ready",
        "running",
        "connected",
        "verified",
        "restored",
        "completed",
        "healthy",
        "true",
        "success",
    }:
        return "ok"

    if text in {
        "warn",
        "warning",
        "degraded",
        "skipped",
        "unknown",
        "planned",
        "starting",
        "stopping",
        "updating",
        "rolling_back",
        "preflight",
        "verifying",
    }:
        return "warn"

    if text in {
        "fail",
        "failed",
        "fail_blocking",
        "error",
        "security_blocked",
        "blocked",
        "quarantined",
        "disconnected",
        "unauthorized",
        "unhealthy",
        "false",
    }:
        return "error"

    return "info"


def render_status(value: Any, label: str | None = None) -> str:
    """Render a canonical status value as a badge."""

    return render_badge(label or raw_value(value), status_tone(value))


def render_card(title: str, body: str = "", *, footer: str = "", classes: str = "") -> str:
    """Render a standard card panel."""

    return safe_html(
        f'<section class="{css_class("kx-card", classes)}">'
        f"<h2>{h(title)}</h2>"
        f"{body}"
        f"{footer}"
        "</section>"
    )


def render_section(title: str, body: str = "", *, intro: str = "") -> str:
    """Render a titled page section."""

    intro_html = f'<p class="kx-muted">{h(intro)}</p>' if intro else ""
    return safe_html(f"<section><h2>{h(title)}</h2>{intro_html}{body}</section>")


def render_grid(cards: Iterable[str]) -> str:
    """Render cards/fragments in a responsive grid."""

    return safe_html(f'<div class="kx-grid">{"".join(cards)}</div>')


def render_empty_state(message: str, *, detail: str = "") -> str:
    """Render an empty state."""

    detail_html = f'<p class="kx-muted">{h(detail)}</p>' if detail else ""
    return render_card("No data", f"<p>{h(message)}</p>{detail_html}")


def render_value(value: Any) -> str:
    """Render scalar/sequence/mapping values safely."""

    if value is None:
        return '<span class="kx-muted">—</span>'

    if isinstance(value, SafeHtml):
        return str(value)

    if isinstance(value, bool):
        return render_status("true" if value else "false")

    if isinstance(value, Enum):
        return h(value.value)

    if isinstance(value, Mapping):
        return render_json_block(value)

    to_dict = getattr(value, "to_dict", None)
    if callable(to_dict):
        return render_json_block(to_dict())

    model_dump = getattr(value, "model_dump", None)
    if callable(model_dump):
        return render_json_block(model_dump())

    if isinstance(value, (list, tuple, set)) and not isinstance(value, (str, bytes)):
        if not value:
            return '<span class="kx-muted">—</span>'
        return "<ul>" + "".join(f"<li>{render_value(item)}</li>" for item in value) + "</ul>"

    return h(value)


def render_definition_list(items: Mapping[str, Any] | Sequence[tuple[str, Any]]) -> str:
    """Render key/value pairs as a definition list."""

    pairs = items.items() if isinstance(items, Mapping) else items
    rows = [f"<dt>{h(key)}</dt><dd>{render_value(value)}</dd>" for key, value in pairs]
    return safe_html(f'<dl class="kx-defs">{"".join(rows)}</dl>')


def render_table(rows: Sequence[Mapping[str, Any]], columns: Sequence[str] | None = None) -> str:
    """Render a safe table from mapping rows."""

    if not rows:
        return '<p class="kx-muted">No records found.</p>'

    if columns is None:
        columns = list(rows[0].keys())

    head = "".join(f"<th>{h(column)}</th>" for column in columns)
    body_rows: list[str] = []

    for row in rows:
        cells = "".join(f"<td>{render_value(row.get(column))}</td>" for column in columns)
        body_rows.append(f"<tr>{cells}</tr>")

    return safe_html(
        '<table class="kx-table">'
        f"<thead><tr>{head}</tr></thead>"
        f"<tbody>{''.join(body_rows)}</tbody>"
        "</table>"
    )


def render_metric(label: str, value: Any, *, hint: str = "") -> str:
    """Render a compact metric card."""

    hint_html = f'<p class="kx-muted">{h(hint)}</p>' if hint else ""

    return render_card(
        label,
        f'<p style="font-size:28px;margin:0 0 4px;">{render_value(value)}</p>{hint_html}',
    )


def render_json_block(data: Any) -> str:
    """Render arbitrary data as escaped JSON."""

    return safe_html(f'<pre class="kx-json">{h(json_text(data))}</pre>')


def render_log_block(text: Any) -> str:
    """Render logs or command output as escaped preformatted text."""

    return safe_html(f'<pre class="kx-log">{h(text)}</pre>')


def render_link(label: str, href: str, *, button: bool = False, external: bool = False) -> str:
    """Render a safe link."""

    target = ' target="_blank" rel="noopener noreferrer"' if external else ""
    cls = ' class="kx-button secondary"' if button else ""
    return safe_html(f'<a{cls} href="{safe_href(href)}"{target}>{h(label)}</a>')


def render_hidden(name: str, value: Any) -> str:
    return safe_html(f'<input type="hidden" name="{attr(name)}" value="{attr(value)}">')


def render_input(
    name: str,
    label: str,
    value: Any = "",
    *,
    field_type: str = "text",
    required: bool = False,
    placeholder: str = "",
    help_text: str = "",
) -> str:
    required_attr = " required" if required else ""
    placeholder_attr = f' placeholder="{attr(placeholder)}"' if placeholder else ""
    help_html = f'<div class="kx-help">{h(help_text)}</div>' if help_text else ""

    return safe_html(
        '<div class="kx-field">'
        f'<label for="{attr(name)}">{h(label)}</label>'
        f'<input id="{attr(name)}" name="{attr(name)}" type="{attr(field_type)}" '
        f'value="{attr(value)}"{placeholder_attr}{required_attr}>'
        f"{help_html}"
        "</div>"
    )


def render_textarea(
    name: str,
    label: str,
    value: Any = "",
    *,
    required: bool = False,
    placeholder: str = "",
    help_text: str = "",
) -> str:
    required_attr = " required" if required else ""
    placeholder_attr = f' placeholder="{attr(placeholder)}"' if placeholder else ""
    help_html = f'<div class="kx-help">{h(help_text)}</div>' if help_text else ""

    return safe_html(
        '<div class="kx-field">'
        f'<label for="{attr(name)}">{h(label)}</label>'
        f'<textarea id="{attr(name)}" name="{attr(name)}"{placeholder_attr}{required_attr}>{h(value)}</textarea>'
        f"{help_html}"
        "</div>"
    )


def render_select(
    name: str,
    label: str,
    options: Sequence[SelectOption | tuple[str, str] | str],
    *,
    value: Any = "",
    required: bool = False,
    help_text: str = "",
) -> str:
    current = str(raw_value(value) or "")
    option_html: list[str] = []

    for option in options:
        if isinstance(option, SelectOption):
            option_value = option.value
            option_label = option.label
            selected = option.selected or option.value == current
        elif isinstance(option, tuple):
            option_value, option_label = option
            selected = str(option_value) == current
        else:
            option_value = str(raw_value(option))
            option_label = option_value
            selected = option_value == current

        selected_attr = " selected" if selected else ""
        option_html.append(
            f'<option value="{attr(option_value)}"{selected_attr}>{h(option_label)}</option>'
        )

    required_attr = " required" if required else ""
    help_html = f'<div class="kx-help">{h(help_text)}</div>' if help_text else ""

    return safe_html(
        '<div class="kx-field">'
        f'<label for="{attr(name)}">{h(label)}</label>'
        f'<select id="{attr(name)}" name="{attr(name)}"{required_attr}>{"".join(option_html)}</select>'
        f"{help_html}"
        "</div>"
    )


def render_checkbox(
    name: str,
    label: str,
    *,
    checked: bool = False,
    value: str = "true",
    help_text: str = "",
) -> str:
    checked_attr = " checked" if checked else ""
    help_html = f'<div class="kx-help">{h(help_text)}</div>' if help_text else ""

    return safe_html(
        '<div class="kx-field">'
        f'<label><input name="{attr(name)}" type="checkbox" value="{attr(value)}"{checked_attr}> {h(label)}</label>'
        f"{help_html}"
        "</div>"
    )


def render_fields(fields: Sequence[FormField | Mapping[str, Any]]) -> str:
    """Render declarative form fields."""

    rendered: list[str] = []

    for field in fields:
        item = FormField(**field) if isinstance(field, Mapping) else field

        if item.field_type == "hidden":
            rendered.append(render_hidden(item.name, item.value))
        elif item.field_type == "textarea":
            rendered.append(
                render_textarea(
                    item.name,
                    item.label,
                    item.value,
                    required=item.required,
                    placeholder=item.placeholder,
                    help_text=item.help_text,
                )
            )
        elif item.field_type == "select":
            rendered.append(
                render_select(
                    item.name,
                    item.label,
                    item.options or [],
                    value=item.value,
                    required=item.required,
                    help_text=item.help_text,
                )
            )
        elif item.field_type == "checkbox":
            rendered.append(
                render_checkbox(
                    item.name,
                    item.label,
                    checked=bool(item.value),
                    help_text=item.help_text,
                )
            )
        else:
            rendered.append(
                render_input(
                    item.name,
                    item.label,
                    item.value,
                    field_type=item.field_type,
                    required=item.required,
                    placeholder=item.placeholder,
                    help_text=item.help_text,
                )
            )

    return safe_html("".join(rendered))


def render_form(
    action: str,
    fields: Sequence[FormField | Mapping[str, Any]] | str = "",
    *,
    method: str = "post",
    submit_label: str = "Submit",
    hidden: Mapping[str, Any] | None = None,
    extra_actions: str = "",
    classes: str = "",
) -> str:
    """Render a safe HTML form."""

    method_value = "post" if method.lower() == "post" else "get"
    hidden_html = "".join(render_hidden(key, value) for key, value in (hidden or {}).items())
    fields_html = fields if isinstance(fields, str) else render_fields(fields)
    form_action = _form_action_href(action)

    return safe_html(
        f'<form class="{css_class("kx-form", classes)}" method="{attr(method_value)}" action="{safe_href(form_action)}">'
        f"{hidden_html}"
        f"{fields_html}"
        '<div class="kx-actions">'
        f'<button class="kx-button" type="submit">{h(submit_label)}</button>'
        f"{extra_actions}"
        "</div>"
        "</form>"
    )


def render_action_form(
    action: Any,
    label: str,
    *,
    payload: Mapping[str, Any] | None = None,
    variant: str = "primary",
    disabled: bool = False,
) -> str:
    """Render a one-button POST form for a canonical GUI action."""

    action_value = raw_value(action)
    disabled_attr = " disabled" if disabled else ""
    button_class = css_class(
        "kx-button",
        "secondary" if variant == "secondary" else None,
        "danger" if variant == "danger" else None,
    )
    hidden_payload = {"action": action_value, **dict(payload or {})}
    hidden_html = "".join(render_hidden(key, value) for key, value in hidden_payload.items())

    return safe_html(
        f'<form method="post" action="{safe_href(action_url(action_value))}" style="display:inline">'
        f"{hidden_html}"
        f'<button class="{button_class}" type="submit"{disabled_attr}>{h(label)}</button>'
        "</form>"
    )


def render_action_bar(actions: Sequence[str]) -> str:
    return safe_html(f'<div class="kx-actions">{"".join(actions)}</div>')


def render_product_info(product: Any) -> str:
    data = to_mapping(product)

    body = render_definition_list(
        {
            "Product": data.get("product_name", PRODUCT_NAME),
            "Manager": data.get("manager_name", MANAGER_NAME),
            "App version": data.get("app_version", APP_VERSION),
            "Param version": data.get("param_version", PARAM_VERSION),
        }
    )

    return render_card("Product", body)


def render_agent_status(agent: Any) -> str:
    data = to_mapping(agent)

    connection = data.get("connection", "unknown")
    body = render_definition_list(
        {
            "Connection": safe_html(render_status(connection)),
            "Connected": data.get("connected"),
            "Version": data.get("version"),
            "Local only": data.get("local_only"),
            "Last seen": data.get("last_seen_at"),
            "Message": data.get("message"),
        }
    )

    return render_card("Agent", body)


def render_notifications(notifications: Sequence[Any]) -> str:
    if not notifications:
        return ""

    rows: list[Mapping[str, Any]] = []
    for item in notifications:
        data = to_mapping(item)
        rows.append(
            {
                "level": data.get("level"),
                "message": data.get("message"),
                "created_at": data.get("created_at"),
            }
        )

    return render_card("Notifications", render_table(rows, ["level", "message", "created_at"]))


def render_capsule_summary(capsule: Any) -> str:
    data = to_mapping(capsule)

    body = render_definition_list(
        {
            "Capsule ID": data.get("capsule_id"),
            "Version": data.get("capsule_version"),
            "App version": data.get("app_version"),
            "Imported": data.get("imported"),
            "Signature": safe_html(render_status("verified" if data.get("signature_verified") else "unknown")),
            "Checksum": safe_html(render_status("verified" if data.get("checksum_verified") else "unknown")),
            "Path": data.get("local_path") or data.get("path"),
        }
    )

    return render_card(str(data.get("capsule_id", "Capsule")), body)


def render_capsules(capsules: Sequence[Any]) -> str:
    if not capsules:
        return render_empty_state("No capsules found.", detail="Build, verify, or import a .kxcap capsule.")

    return render_grid(render_capsule_summary(capsule) for capsule in capsules)


def render_network_state(network: Any) -> str:
    data = to_mapping(network)

    return render_definition_list(
        {
            "Profile": data.get("profile") or data.get("network_profile"),
            "Exposure": data.get("exposure_mode"),
            "Public mode": data.get("public_mode_enabled"),
            "Expires": data.get("public_mode_expires_at"),
            "Host": data.get("host"),
            "URL": data.get("url"),
            "Is public": data.get("is_public"),
        }
    )


def render_service_views(services: Sequence[Any]) -> str:
    rows: list[Mapping[str, Any]] = []

    for service in services:
        data = to_mapping(service)
        rows.append(
            {
                "service": data.get("service"),
                "status": safe_html(render_status(data.get("status_label") or data.get("status"))),
                "running": data.get("running"),
                "healthy": data.get("healthy"),
                "desired": data.get("desired"),
                "message": data.get("message"),
            }
        )

    return render_table(rows, ["service", "status", "running", "healthy", "desired", "message"])


def render_health_view(health: Any) -> str:
    data = to_mapping(health)
    services = data.get("services") or []

    body = render_definition_list(
        {
            "Healthy": data.get("healthy"),
            "Ready": data.get("ready"),
            "Message": data.get("message"),
            "Checked at": data.get("checked_at"),
        }
    )

    if services:
        body += "<h3>Services</h3>"
        body += render_service_views(services)

    return safe_html(body)


def render_security_gate_view(security_gate: Any) -> str:
    data = to_mapping(security_gate)
    checks = data.get("checks") or []

    body = render_definition_list(
        {
            "Status": safe_html(render_status(data.get("status", "unknown"))),
            "Passed": data.get("passed"),
            "Blocking failures": data.get("blocking_failures"),
            "Checked at": data.get("checked_at"),
        }
    )

    if checks:
        rows: list[Mapping[str, Any]] = []
        for check in checks:
            item = to_mapping(check)
            rows.append(
                {
                    "check": item.get("check"),
                    "status": safe_html(render_status(item.get("status"))),
                    "blocking": item.get("blocking"),
                    "blocks_startup": item.get("blocks_startup"),
                    "message": item.get("message"),
                }
            )

        body += "<h3>Checks</h3>"
        body += render_table(rows, ["check", "status", "blocking", "blocks_startup", "message"])

    return safe_html(body)


def render_backup_summary(backup: Any) -> str:
    data = to_mapping(backup)

    return render_definition_list(
        {
            "Backup ID": data.get("backup_id"),
            "Instance": data.get("instance_id"),
            "Status": safe_html(render_status(data.get("status"))),
            "Class": data.get("backup_class"),
            "Usable for restore": data.get("usable_for_restore"),
            "Path": data.get("display_path") or data.get("root_dir"),
            "Created": data.get("created_at"),
            "Verified": data.get("verified_at"),
            "Error": data.get("error"),
        }
    )


def render_backups(backups: Sequence[Any]) -> str:
    if not backups:
        return render_empty_state("No backups found.")

    rows: list[Mapping[str, Any]] = []
    for backup in backups:
        data = to_mapping(backup)
        rows.append(
            {
                "backup_id": data.get("backup_id"),
                "instance_id": data.get("instance_id"),
                "status": safe_html(render_status(data.get("status"))),
                "backup_class": data.get("backup_class"),
                "usable_for_restore": data.get("usable_for_restore"),
                "created_at": data.get("created_at"),
            }
        )

    return render_table(
        rows,
        ["backup_id", "instance_id", "status", "backup_class", "usable_for_restore", "created_at"],
    )


def render_instance_summary(instance: Any) -> str:
    data = to_mapping(instance)
    instance_id = data.get("instance_id", "Instance")

    network = data.get("network") or {}
    health = data.get("health") or {}
    security_gate = data.get("security_gate") or data.get("security") or {}
    last_backup = data.get("last_backup") or data.get("latest_backup")

    overview = render_definition_list(
        {
            "State": safe_html(render_status(data.get("state"))),
            "Capsule": data.get("capsule_id"),
            "Capsule version": data.get("capsule_version"),
            "Can start": data.get("can_start"),
            "Can stop": data.get("can_stop"),
            "Can backup": data.get("can_backup"),
            "Blocked by security": data.get("blocked_by_security"),
            "Updated": data.get("updated_at"),
        }
    )

    body = overview
    body += "<h3>Network</h3>" + render_network_state(network)
    body += "<h3>Health</h3>" + render_health_view(health)
    body += "<h3>Security Gate</h3>" + render_security_gate_view(security_gate)

    if last_backup:
        body += "<h3>Last backup</h3>" + render_backup_summary(last_backup)

    actions = render_action_bar(
        [
            render_action_form("instance_status", "Status", payload={"instance_id": instance_id}, variant="secondary"),
            render_action_form("view_health", "Health", payload={"instance_id": instance_id}, variant="secondary"),
            render_action_form("view_logs", "Logs", payload={"instance_id": instance_id}, variant="secondary"),
            render_action_form(
                "start_instance",
                "Start",
                payload={"instance_id": instance_id},
                disabled=not bool(data.get("can_start")),
            ),
            render_action_form(
                "stop_instance",
                "Stop",
                payload={"instance_id": instance_id},
                variant="danger",
                disabled=not bool(data.get("can_stop")),
            ),
        ]
    )

    return render_card(str(instance_id), body, footer=actions)


def render_instances(instances: Sequence[Any]) -> str:
    if not instances:
        return render_empty_state("No instances found.", detail="Create an instance from an imported capsule.")

    return render_grid(render_instance_summary(instance) for instance in instances)


def render_log_entries(entries: Sequence[Any]) -> str:
    if not entries:
        return render_empty_state("No log entries found.")

    rows: list[Mapping[str, Any]] = []

    for entry in entries:
        data = to_mapping(entry)
        rows.append(
            {
                "timestamp": data.get("timestamp"),
                "level": data.get("level"),
                "source": data.get("source"),
                "service": data.get("service"),
                "message": data.get("message"),
            }
        )

    return render_table(rows, ["timestamp", "level", "source", "service", "message"])


def render_manager_state_dashboard(state: Any) -> str:
    """Render a dashboard from ManagerState or a compatible mapping."""

    data = to_mapping(state)

    product = data.get("product", {})
    agent = data.get("agent", {})
    capsules = data.get("capsules") or []
    instances = data.get("instances") or []
    backups = data.get("backups") or []
    notifications = data.get("notifications") or []

    metrics = render_grid(
        [
            render_metric("Capsules", len(capsules), hint="Available or imported capsules"),
            render_metric("Instances", len(instances), hint="Known Konnaxion instances"),
            render_metric(
                "Running",
                data.get("running_instance_count", 0),
                hint="Instances currently running",
            ),
            render_metric(
                "Security blocked",
                data.get("security_blocked_instance_count", 0),
                hint="Instances blocked by Security Gate",
            ),
        ]
    )

    body = ""
    body += render_notifications(notifications)
    body += metrics
    body += render_grid([render_product_info(product), render_agent_status(agent)])
    body += render_section("Instances", render_instances(instances))
    body += render_section("Capsules", render_capsules(capsules))
    body += render_section("Backups", render_backups(backups))

    return safe_html(body)


def render_manager_state_page(state: Any, *, result: Any | None = None) -> HTMLResponse:
    """Render the main Manager dashboard page."""

    return html_response(
        "Konnaxion Capsule Manager",
        render_manager_state_dashboard(state),
        subtitle="Local-only capsule, instance, security, network, backup, and deployment control.",
        active_href="/ui",
        result=result,
    )


def render_messages(messages: Sequence[str] | None, *, tone: str = "info") -> str:
    if not messages:
        return ""

    items = "".join(f"<li>{h(message)}</li>" for message in messages)
    return render_card("Messages", f"<ul>{items}</ul>", classes=f"kx-result {tone}")


def render_result_panel(result: Any | None) -> str:
    """Render a normalized GUI action result."""

    if result is None:
        return ""

    data = to_mapping(result)

    if data:
        ok = bool(data.get("ok", data.get("success", False)))
        action = data.get("action", data.get("operation", ""))
        message = data.get("message", "")
        instance_id = data.get("instance_id", "")
        payload = data.get("data", data.get("payload", None))
    else:
        ok = bool(getattr(result, "ok", getattr(result, "success", False)))
        action = getattr(result, "action", getattr(result, "operation", ""))
        message = getattr(result, "message", "")
        instance_id = getattr(result, "instance_id", "")
        payload = getattr(result, "data", getattr(result, "payload", None))

    tone = "ok" if ok else "error"

    body = f"<p>{h(message or ('Action completed.' if ok else 'Action failed.'))}</p>"
    body += render_definition_list(
        {
            "ok": ok,
            "action": action,
            "instance_id": instance_id,
        }
    )

    if payload not in (None, {}, []):
        body += "<h3>Data</h3>" + render_json_block(payload)

    return render_card("Result", body, classes=f"kx-result {tone}")


__all__ = [
    "ACTION_BASE_PATH",
    "BASE_CSS",
    "DEFAULT_TITLE",
    "MANAGER_NAME",
    "PRODUCT_NAME",
    "SafeHtml",
    "UI_BASE_PATH",
    "FormField",
    "NavItem",
    "SelectOption",
    "action_url",
    "attr",
    "css_class",
    "default_nav",
    "h",
    "html_response",
    "json_text",
    "raw_value",
    "render_action_bar",
    "render_action_form",
    "render_agent_status",
    "render_backup_summary",
    "render_backups",
    "render_badge",
    "render_card",
    "render_capsule_summary",
    "render_capsules",
    "render_checkbox",
    "render_definition_list",
    "render_empty_state",
    "render_error_page",
    "render_fields",
    "render_form",
    "render_grid",
    "render_header",
    "render_health_view",
    "render_hidden",
    "render_input",
    "render_instance_summary",
    "render_instances",
    "render_json_block",
    "render_layout",
    "render_link",
    "render_log_block",
    "render_log_entries",
    "render_manager_state_dashboard",
    "render_manager_state_page",
    "render_messages",
    "render_metric",
    "render_nav",
    "render_network_state",
    "render_notifications",
    "render_page",
    "render_product_info",
    "render_result_panel",
    "render_section",
    "render_security_gate_view",
    "render_select",
    "render_service_views",
    "render_status",
    "render_table",
    "render_textarea",
    "render_value",
    "safe_href",
    "safe_html",
    "status_tone",
    "to_mapping",
]